#!/usr/bin/env python3
"""Build deterministic, single-artifact pip locks for the release platform.

The input directory must contain exactly one wheel for every pin in
``requirements-ci.txt`` and nothing else.  The wheel selection is intentionally
performed separately with an explicit target platform; this script then proves
the selection matches the reviewed flat graphs and records each artifact hash.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

from packaging.utils import parse_wheel_filename

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from scripts.check_runtime_environment import (
    PROJECT_ROOT,
    PRODUCTION_REQUIREMENTS,
    RuntimeContractError,
    canonical_package_name,
    parse_exact_pins,
    read_exact_pins,
)


CI_REQUIREMENTS = PROJECT_ROOT / "requirements-ci.txt"
PRODUCTION_LOCK = (
    PROJECT_ROOT / "deploy" / "cloud-run" / "requirements-prod-linux-x86_64.lock"
)
CI_LOCK = PROJECT_ROOT / "requirements-ci-linux-x86_64.lock"
EXPECTED_INCLUDE = "-r deploy/cloud-run/requirements-prod.txt"
SHA256 = re.compile(r"[0-9a-f]{64}\Z")

HEADER = """# Generated by scripts/build_linux_wheel_locks.py; DO NOT EDIT.
# Target: CPython 3.12.10, Linux x86_64, Debian bookworm (glibc 2.36).
# Selector: pip 25.0.1 with explicit compatible platform and ABI tags.
# Every requirement permits exactly one reviewed wheel byte sequence.
# Install with: pip install --no-deps --only-binary=:all: --require-hashes -r <lock>
"""


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_ci_only_pins(path: Path = CI_REQUIREMENTS) -> dict[str, str]:
    """Read the strict CI extension file and reject hidden resolution inputs."""

    active = [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    includes = [line for line in active if line.startswith(("-r", "--requirement"))]
    if includes != [EXPECTED_INCLUDE]:
        raise RuntimeContractError(
            f"{path} must include only {EXPECTED_INCLUDE!r} before exact CI pins"
        )

    pin_lines = [line for line in active if line not in includes]
    return parse_exact_pins(pin_lines, source=str(path))


def inspect_wheels(wheel_dir: Path) -> dict[str, tuple[str, str, int, str]]:
    """Return package -> (version, filename, bytes, sha256) for an exact wheel set."""

    if not wheel_dir.is_dir():
        raise RuntimeContractError(f"wheel directory is missing: {wheel_dir}")
    unexpected = sorted(path.name for path in wheel_dir.iterdir() if path.suffix != ".whl")
    if unexpected:
        raise RuntimeContractError(
            f"wheel directory contains non-wheel entries: {', '.join(unexpected)}"
        )

    artifacts: dict[str, tuple[str, str, int, str]] = {}
    for path in sorted(wheel_dir.glob("*.whl"), key=lambda item: item.name.lower()):
        try:
            distribution, version, _build, _tags = parse_wheel_filename(path.name)
        except Exception as exc:
            raise RuntimeContractError(f"invalid wheel filename: {path.name}") from exc
        package = canonical_package_name(str(distribution))
        if package in artifacts:
            raise RuntimeContractError(f"multiple wheel artifacts found for {package}")
        digest = _sha256(path)
        if not SHA256.fullmatch(digest):  # pragma: no cover - hashlib invariant
            raise RuntimeContractError(f"invalid SHA-256 result for {path.name}")
        artifacts[package] = (str(version), path.name, path.stat().st_size, digest)
    if not artifacts:
        raise RuntimeContractError(f"wheel directory contains no wheels: {wheel_dir}")
    return artifacts


def render_lock(
    pins: dict[str, str],
    artifacts: dict[str, tuple[str, str, int, str]],
) -> str:
    """Render one stable pip hash lock while preserving reviewed pin order."""

    missing = sorted(set(pins) - set(artifacts))
    if missing:
        raise RuntimeContractError(f"missing wheels for: {', '.join(missing)}")

    lines = [HEADER.rstrip(), f"# Artifact count: {len(pins)}"]
    for package, expected_version in pins.items():
        actual_version, filename, byte_count, digest = artifacts[package]
        if actual_version != expected_version:
            raise RuntimeContractError(
                f"wheel version mismatch for {package}: {actual_version}; "
                f"expected {expected_version}"
            )
        lines.extend(
            (
                f"# wheel: {filename} ({byte_count} bytes)",
                f"{package}=={expected_version} --hash=sha256:{digest}",
            )
        )
    return "\n".join(lines) + "\n"


def build_outputs(wheel_dir: Path) -> dict[Path, str]:
    production = read_exact_pins(PRODUCTION_REQUIREMENTS)
    ci_only = read_ci_only_pins()
    overlap = sorted(set(production) & set(ci_only))
    if overlap:
        raise RuntimeContractError(f"CI pins duplicate production pins: {', '.join(overlap)}")
    ci = {**production, **ci_only}
    artifacts = inspect_wheels(wheel_dir)
    extra = sorted(set(artifacts) - set(ci))
    if extra:
        raise RuntimeContractError(f"unreviewed wheels present: {', '.join(extra)}")
    return {
        PRODUCTION_LOCK: render_lock(production, artifacts),
        CI_LOCK: render_lock(ci, artifacts),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wheel-dir", type=Path, required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    try:
        outputs = build_outputs(args.wheel_dir)
        if args.write:
            for path, payload in outputs.items():
                path.write_text(payload, encoding="utf-8", newline="\n")
        else:
            mismatched = [
                path
                for path, expected in outputs.items()
                if not path.is_file() or path.read_text(encoding="utf-8") != expected
            ]
            if mismatched:
                raise RuntimeContractError(
                    "wheel lock differs from selected artifacts: "
                    + ", ".join(str(path) for path in mismatched)
                )
    except (OSError, RuntimeContractError) as exc:
        print(f"Linux wheel lock: BLOCKED\n- {exc}", file=sys.stderr)
        return 1

    verb = "wrote" if args.write else "verified"
    print(f"Linux wheel lock: PASS ({verb} {len(outputs)} locks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
