[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"

[server]
fileWatcherType = "none"
enableCORS = true
enableXsrfProtection = true
enableStaticServing = false
maxUploadSize = 20
maxMessageSize = 25
disconnectedSessionTTL = 120
